# -*- coding: utf-8 -*-
"""Chores_FM_Simplex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UWzKTjo8GWyR-PaZH69k-k3eGSiCNGO
"""

import numpy as np
import cvxpy as cp

from scipy.optimize import linprog

from gfw import *

def find_basic_feasible_solution(A, b, x_feasible=None):
    """
    Finds a basic feasible solution of a polytope defined by Ax <= b.

    Args:
        A (np.array): The matrix of coefficients for the inequality constraints.
        b (np.array): The right-hand side vector for the inequality constraints.
        x_feasible (np.array, optional): An initial feasible solution.
                                        Not strictly necessary for linprog,
                                        but can be used for warm-starting if needed.

    Returns:
        np.array: A basic feasible solution (vertex) of the polytope,
                  or None if no feasible solution exists.
    """
    num_variables = A.shape[1]
    # Create a dummy objective function (e.g., minimize all zeros)
    c = np.zeros(num_variables)

    # Use linprog to find a basic feasible solution
    # The 'highs' method is generally recommended for performance
    result = linprog(c, A_eq=A, b_eq=b, bounds=(0, None))

    if result.success:
        return result.x
    else:
        print("No feasible solution found.")
        return None

def find_x(N, M, D, B, p, tol=1e-6):

    x = cp.Variable(shape=(N, M), name="x")
    objective = cp.Minimize(0)

    constraints = []
    # mpp constraints
    p_D = p / D
    mpp = np.amax(p_D, axis=1)
    for i in range(N):
        for j in range(M):
            if abs(p_D[i][j] - mpp[i]) > tol:
                constraints.append(x[i, j] == 0)
    # budget constraints
    for i in range(N):
        constraints.append(cp.sum(cp.multiply(p, x[i, :])) == B[i])
    # market clearing
    for j in range(M):
        constraints.append(cp.sum(x[:, j]) == 1)

    prob = cp.Problem(objective, constraints)
    prob.solve()

    return x.value

from copy import deepcopy

def reduced_costs(A, b, c, basis):

    _, num_var = A.shape
    B = A[:, basis]
    c_B = c[basis]

    # dual prices (y = c_B^T B^{-1})
    y = np.linalg.solve(B.T, c_B)

    # reduced costs
    rc = np.zeros(num_var)
    for j in range(num_var):
        if j not in basis:
            rc[j] = c[j] - y @ A[:, j]

    return rc

def pick_entering_var(rc, rule="Min"):

    all_neg = []
    all_neg_vals = []
    for i in range(len(rc)):
        if rc[i] < -1e-9:
            all_neg.append(i)
            all_neg_vals.append((float(rc[i]), i))
    if len(all_neg) == 0:
        return -1
    all_neg = np.sort(all_neg)
    all_neg_vals = sorted(all_neg_vals, key=lambda x: x[0])

    # print("Pick an entering variable from", all_neg_vals)

    if rule == "Brand":
        return all_neg[0]
    elif rule == "Random":
        return np.random.choice(all_neg)
    elif rule == "Min":
        return all_neg_vals[0][1]

    raise ValueError("Invalid rule")

def pick_leaving_var(A, b, x, entering_var, basis, rule="Brand"):

    Binv_Ae = np.linalg.solve(A[:, basis], A[:, entering_var])
    move_vector = Binv_Ae
    # print("Binv_Ae:")
    # for entry in Binv_Ae:
    #     print(entry, end=" ")
    # print()

    # THIS CASE SHOULD NOT HAPPEN
    if max(Binv_Ae) <= 1e-12:
        return "The problem is unbounded"

    mrt_list = []
    mrt_details_list = []
    Binv_b = np.linalg.solve(A[:, basis], b)

    for i in range(len(basis)):
        if Binv_Ae[i] > 0 and Binv_b[i] >= 0:
            theta_i = Binv_b[i] / Binv_Ae[i]
            mrt_list.append(theta_i)
            mrt_details_list.append((theta_i, Binv_b[i], Binv_Ae[i]))

    # sort mrt_details_list
    mrt_details_list = sorted(mrt_details_list, key=lambda x: x[0])
    # print("mrt_details_list", mrt_details_list)

    mrt_list = np.array(mrt_list)
    mrt_list = mrt_list[mrt_list > 0]

    theta = min(mrt_list)
    # print("theta", theta)

    # print("x[basis]:")
    # for entry in x[basis]:
    #     print(entry, end=" ")
    # print()
    # print("Binv_b:")
    # for entry in Binv_b:
    #     print(entry, end=" ")

    all_min_ratio = []
    x_new_basis = x[basis] - theta * move_vector
    # x_new_basis is a full-length x vector
    min_x_new_basis = min(x_new_basis)
    for i in range(len(x_new_basis)):
        if x_new_basis[i] <= min_x_new_basis + 1e-12:
            all_min_ratio.append(i)

    # print(theta, all_min_ratio)

    if len(all_min_ratio) == 1:
        return all_min_ratio, theta, move_vector

    if rule == "Brand":
        return all_min_ratio[0], theta, move_vector
    elif rule == "Random":
        return np.random.choice(all_min_ratio), theta, move_vector

def pivot(A, b, c, x, basis, precision=3, entering_var_rule="Min"):

    status = "continue"

    log = ""
    # log += "current basis: " + str(basis) + "\n"
    # log += "current point: " + str(np.round(x, precision)) + "\n"
    # log += "current objective value: " + str(np.round(np.dot(c, x), precision)) + "\n"

    rc = reduced_costs(A, b, c, basis)
    # print("[reduced costs] ->", rc)
    # print("[minimum reduced costs] ->", min(rc), "(", np.argmin(rc), ")")
    # log += "reduced costs: " + str(np.round(rc, precision)) + "\n"

    # print("To pick an entering variable")
    entering_var = pick_entering_var(rc, rule=entering_var_rule)
    if entering_var == -1:
        log += "The current solution is optimal"
        status = "optimal"
        return x, basis, log, status

    # print("Entering variable:", entering_var)
    log += "entering variable: " + str(entering_var) + "\n"

    leaving_var, theta, move_vector = pick_leaving_var(A, b, x, entering_var, basis, rule="Brand")
    if type(leaving_var) == list:
        leaving_var = leaving_var[0]
        basis[leaving_var] = entering_var
        new_basis = np.sort(basis)
    else:
        temp_new_basis = deepcopy(basis)
        temp_new_basis[leaving_var] = entering_var
        count = 0
        while np.linalg.matrix_rank(A[:, temp_new_basis]) < M * N + 1 and count < 10:
            print(np.linalg.matrix_rank(A[:, temp_new_basis]))
            temp_new_basis = np.sort(temp_new_basis)
            print(temp_new_basis)
            for i in range(len(A)):
                print(A[i, temp_new_basis])
            leaving_var, theta, move_vector = pick_leaving_var(A, b, x, entering_var, basis, rule="Random")
            temp_new_basis = deepcopy(basis)
            temp_new_basis[leaving_var] = entering_var
            count += 1

        new_basis = np.sort(temp_new_basis)

    # print(">>> Test new basis <<<")
    # print(new_basis)
    # print(np.linalg.matrix_rank(A[:, new_basis]))
    # print("Binv_b", np.linalg.solve(A[:, new_basis], b))

    log += "leaving variable: " + str(leaving_var) + "\n"
    log += "theta: " + str(np.round(theta, precision)) + "\n"

    # print("confirm entering and leaving variables")

    # print("previous point", x)
    next_point = np.zeros(A.shape[1])
    next_point[new_basis] = np.linalg.solve(A[:, new_basis], b)
    # print("new point computed by the new basis", next_point)

    new_point = x.copy()
    new_point[basis] -= theta * move_vector
    new_point[entering_var] = theta
    # print("new point computed by the moving vector", new_point)

    # log += "next basis: " + str(new_basis) + "\n"
    # log += "next point: " + str(np.round(new_point, precision)) + "\n"
    # log += "next objective value: " + str(np.round(np.dot(c, new_point), precision))

    return new_point, new_basis, log, status

def update_c(x, N, B):

    return np.concatenate([B / x[:N], np.zeros(M + M * N)])

def polytope_dual(N, M, D, B):
    A = list()
    # when using Gurobi, do not include the nonnegative constraints
    for i in range(N):
        D_i_T = np.zeros(shape=(M, N))
        D_i_T[:, i] = - D[i]
        A_i = np.concatenate([D_i_T, np.identity(M)], axis=1)
        A.append(A_i)
    A = np.concatenate(A, axis=0)
    b = np.zeros(shape=(M * N))
    C = np.concatenate([np.zeros(N), np.ones(M)]).reshape(1, -1)
    d = np.array(sum(B)).reshape(1, )

    return A, b, C, d

def standard_form(A, b, C, d):
    r1, c1 = A.shape
    r2, c1 = C.shape
    c2 = r1

    AI = np.concatenate([A, np.identity(r1)], axis=1)
    new_A = np.concatenate([AI, np.concatenate([C, np.zeros(shape=(r2, c2))], axis=1)], axis=0)
    new_b = np.concatenate([b, d], axis=0)

    return new_A, new_b

def Simplex(N, M, D, B, report_total_pivots=True): 
    A, b, C, d = polytope_dual(N, M, D, B)
    A, b = standard_form(A, b, C, d)

    # initialize
    x = find_basic_feasible_solution(A, b)  # x is the concatenation of \beta, p, s
    # print("log-NSW:", sum(B * np.log(x[:N])))
    # print("initial x: \n", x)

    basis = np.where(x > 1e-6)[0]
    zeros_in_x = np.where(x <= 1e-6)[0]
    while len(basis) < N * M + 1:
        # randomly pick one element from `zeros_in_x`, if it is linear independent with the current basis, add it to the basis
        random_index = np.random.choice(zeros_in_x)
        temp_basis = np.concatenate([basis, [random_index]])
        if np.linalg.matrix_rank(A[:, temp_basis]) > np.linalg.matrix_rank(A[:, basis]):
            basis = temp_basis
            zeros_in_x = np.delete(zeros_in_x, np.where(zeros_in_x == random_index))
            print(len(basis))

    # print(len(basis))
    # print("initial basis: \n", basis)

    c = np.concatenate([B / x[:N], np.zeros(M + M * N)])
    # print("initial c: \n", c)
    # print("-------------------------------------------------------")

    total_pivots_Simplex = 0
    status = "continue"
    i = 0
    while status == "continue" and i <= 3000:
        # print("> To proceed with another pivot")
        x_ = x
        x, basis, log, status = pivot(A, b, c, x, basis)
        if status == "continue":
            total_pivots_Simplex += 1
        # print("The distance x moved in l2 norm:", (sum((x - x_) ** 2)) ** (1/2))
        c = update_c(x, N, B)
        # print(log)
        # print("log-NSW:", sum(B * np.log(x[:N])))
        # print("-------------------------------------------------------")

        i += 1

        if i % 10 == 0: 
            print("o", end ="", flush=True)

    print()
    if i > 3000:
        print("The algorithm reach the preset iteration limit")

    return total_pivots_Simplex 

size_list = [20, 60, 100]

data = {
    "size": [],
    "total_pivots_GFW": [],
    "total_pivots_Simplex": [],
}
for size in size_list: 
    stats_data = {
        "size": size,
        "total_pivots_GFW": [],
        "total_pivots_Simplex": [],
    }
    for i in range(10): 
        N, M = size, size
        np.random.seed(i)
        D, B = np.random.uniform(size=(N, M)), np.ones(N)

        """
        Solve with GFW
        """
        _, _, _, _, _, _, total_pivots_GFW = GFW(N, M, D, B, warm_start=True, LP_solve_method="primal simplex", report_total_pivots=True)


        """
        Solve with "Simplex"
        """
        total_pivots_Simplex = Simplex(N, M, D, B, report_total_pivots=True)

        print("Size of the instance: N =", N, ", M =", M, "Pivots in GFW:", total_pivots_GFW, ", Pivots in Simplex:", total_pivots_Simplex)
        stats_data["total_pivots_GFW"].append(total_pivots_GFW)
        stats_data["total_pivots_Simplex"].append(total_pivots_Simplex)

    print("Average number of pivots in GFW:", np.mean(stats_data["total_pivots_GFW"]))
    print("Average number of pivots in Simplex:", np.mean(stats_data["total_pivots_Simplex"]))
    data["size"].append(size)
    data["total_pivots_GFW"].append(np.mean(stats_data["total_pivots_GFW"]))
    data["total_pivots_Simplex"].append(np.mean(stats_data["total_pivots_Simplex"]))

import pandas as pd
df = pd.DataFrame(data)
df.to_csv("chores_fm_simplex.csv", index=False)