# -*- coding: utf-8 -*-
"""Plot welfare metrics (utilitarian, egalitarian, nash) vs problem size.

This script reads a welfare CSV generated by run_simulation.py and saves one
figure with three subplots:
  - utilitarian welfare
  - egalitarian welfare
  - nash welfare

Each subplot compares GFW, EPM, and COMB exact variants when available.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ALGORITHMS = {
    "GFW": {"label": "GFW", "color": "darkgreen", "marker": "^", "zorder": 3},
    "EPM": {"label": "EPM", "color": "darkorange", "marker": "*", "zorder": 2},
    "COMB": {"label": "COMB", "color": "royalblue", "marker": "o", "zorder": 1},
}

WELFARE_METRICS = ["utilitarian", "egalitarian", "nash"]


def parse_size_label(size_text: str) -> tuple[float, str]:
    """Return (numeric_size, display_label) from size strings like '12x12'."""
    size_text = str(size_text).strip()
    if "x" in size_text:
        left, right = size_text.split("x", 1)
        try:
            left_n = float(left)
            right_n = float(right)
            if left_n == right_n:
                return left_n, str(int(left_n)) if float(left_n).is_integer() else str(left_n)
            # Rectangular instance: use area for ordering while keeping full label.
            return left_n * right_n, size_text
        except ValueError:
            pass

    try:
        val = float(size_text)
        label = str(int(val)) if float(val).is_integer() else str(val)
        return val, label
    except ValueError:
        # Fallback: preserve order by returning NaN numeric key.
        return np.nan, size_text


def prepare_size_axis(df: pd.DataFrame) -> tuple[np.ndarray, list[str], pd.DataFrame]:
    if "size" not in df.columns:
        raise ValueError("Input CSV must contain a 'size' column.")

    parsed = df["size"].apply(parse_size_label)
    size_numeric = parsed.apply(lambda x: x[0])
    size_label = parsed.apply(lambda x: x[1])

    out = df.copy()
    out["_size_numeric"] = size_numeric
    out["_size_label"] = size_label

    # Keep original row order when numeric keys are all missing.
    if out["_size_numeric"].notna().any():
        out = out.sort_values(by=["_size_numeric"], kind="stable")

    x = np.arange(len(out), dtype=int)
    labels = out["_size_label"].astype(str).tolist()
    return x, labels, out


def plot_welfare(csv_path: Path, output_dir: Path) -> Path:
    df = pd.read_csv(csv_path)
    x, x_labels, data = prepare_size_axis(df)

    fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharex=True)

    for ax, metric in zip(axes, WELFARE_METRICS):
        for algo, style in ALGORITHMS.items():
            col = f"{metric}_{algo}_e"
            if col not in data.columns:
                continue

            y = pd.to_numeric(data[col], errors="coerce")
            valid = y.notna().to_numpy()
            if not np.any(valid):
                continue

            ax.scatter(
                x[valid],
                y.to_numpy()[valid],
                label=style["label"],
                color=style["color"],
                marker=style["marker"],
                linewidth=2.5,
                zorder=style["zorder"],
            )

            if ax == axes[2]:
                ax.set_yscale("log")

        ax.set_title(metric.capitalize(), fontsize=16)
        ax.set_xlabel("Problem size", fontsize=13)
        ax.grid(True, alpha=0.25)

    axes[0].set_ylabel("Welfare value", fontsize=13)

    for ax in axes:
        ax.set_xticks(x)
        ax.set_xticklabels(x_labels, rotation=45, ha="right")
        ax.tick_params(axis="both", labelsize=11)
        ax.legend(fontsize=11)

    fig.tight_layout()

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{csv_path.stem}_welfare_subplots.png"
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot welfare metrics from a welfare CSV.")
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("../data/randint10_5x5.10x10....50x50_welfare_10.csv"),
        help="Path to the welfare CSV file.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("../figures"),
        help="Directory where the output figure is saved.",
    )

    args = parser.parse_args()

    current_dir = Path(__file__).parent.resolve()
    csv_dir = current_dir / "../data"
    csv_path = csv_dir / "randint10_5x5.10x10....80x80_welfare_10.csv"
    output_dir = current_dir / "../figures"

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    output_path = plot_welfare(csv_path=csv_path, output_dir=output_dir)
    print(f"Saved: {output_path}")


if __name__ == "__main__":
    main()
